import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Rocket, Brain, Target, Zap, Cpu, Code2, Share2 } from 'lucide-react';
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const Landing = () => {
  // Animation Variants
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.3, delayChildren: 0.2 }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1, transition: { duration: 0.8, ease: "easeOut" } }
  };

  const features = [
    { 
      icon: <Brain className="text-blue-500" />, 
      title: "AI Roadmaps", 
      desc: "Deep-learning curriculums generated by CogniLit AI." 
    },
    { 
      icon: <Target className="text-emerald-500" />, 
      title: "Goal Tracking", 
      desc: "Automated progress syncing with your career objectives." 
    },
    { 
      icon: <Zap className="text-orange-500" />, 
      title: "Interactive Labs", 
      desc: "Dockerized environments for real-time coding practice." 
    }
  ];

  return (
    <div className="min-h-screen bg-white overflow-hidden">
      {/* Background Ambient "Gestures" */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <motion.div 
          animate={{ scale: [1, 1.2, 1], opacity: [0.3, 0.5, 0.3] }}
          transition={{ duration: 8, repeat: Infinity }}
          className="absolute -top-[10%] -left-[10%] w-[40%] h-[40%] bg-blue-50 rounded-full blur-[120px]" 
        />
        <motion.div 
          animate={{ scale: [1, 1.3, 1], opacity: [0.2, 0.4, 0.2] }}
          transition={{ duration: 10, repeat: Infinity, delay: 1 }}
          className="absolute top-[20%] -right-[10%] w-[30%] h-[30%] bg-indigo-50 rounded-full blur-[100px]" 
        />
      </div>

      {/* Hero Section */}
      <section className="relative max-w-7xl mx-auto px-6 pt-32 pb-20 text-center">
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate="visible"
        >
          {/* Gesture 1: The Badge Reveal */}
          <motion.div variants={itemVariants}>
            <Badge className="mb-6 bg-slate-900 text-white px-4 py-1.5 rounded-full hover:bg-slate-800 border-none transition-all">
              Skillinex Engine v2.4 
            </Badge>
          </motion.div>

          {/* Gesture 2: The Headline Blast */}
          <motion.h1 
            variants={itemVariants}
            className="text-6xl md:text-8xl font-black text-slate-900 tracking-tighter leading-[0.9]"
          >
            THE FUTURE OF <br />
            <span className="text-primary bg-gradient-to-r from-blue-600 via-indigo-600 to-blue-500 bg-clip-text text-transparent">
              TECHNICAL MASTERY.
            </span>
          </motion.h1>
          
          <motion.p 
            variants={itemVariants}
            className="mt-10 text-xl text-slate-500 max-w-2xl mx-auto font-medium"
          >
            One prompt. One roadmap. Total domain dominance. 
            Skillinex builds your path; you just walk it.
          </motion.p>

          {/* Gesture 3: The Primary Call to Action */}
          <motion.div 
            variants={itemVariants}
            className="mt-12 flex flex-col sm:flex-row justify-center gap-6"
          >
            <Button asChild size="lg" className="h-16 px-12 text-lg rounded-2xl shadow-2xl shadow-blue-200 bg-primary hover:bg-blue-700 transition-all">
              <Link to="/signup" className="flex items-center gap-2">
                Initialize Roadmap <Rocket size={20} />
              </Link>
            </Button>
            <Button asChild variant="outline" size="lg" className="h-16 px-12 text-lg rounded-2xl border-slate-200 hover:bg-slate-50">
              <Link to="/login">Access Dashboard</Link>
            </Button>
          </motion.div>
        </motion.div>

        {/* Gesture 4: Floating Tech Matrix */}
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.5, duration: 1 }}
          className="mt-32 pt-10 border-t border-slate-100 relative"
        >
          <div className="flex flex-wrap justify-center gap-12 grayscale opacity-40">
             {[
               { icon: <Code2 size={24}/>, name: "React" },
               { icon: <Cpu size={24}/>, name: "FastAPI" },
               { icon: <Share2 size={24}/>, name: "Docker" },
               { icon: <Zap size={24}/>, name: "Redis" }
             ].map((tech, i) => (
               <motion.div 
                 key={i}
                 animate={{ y: [0, -10, 0] }}
                 transition={{ duration: 4, repeat: Infinity, delay: i * 0.5 }}
                 className="flex items-center gap-2 font-bold text-slate-900"
               >
                 {tech.icon} <span>{tech.name}</span>
               </motion.div>
             ))}
          </div>
        </motion.div>
      </section>

      {/* Features: The "Expansion" Grid */}
      <section className="relative py-32 bg-slate-50/50">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            {features.map((feature, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.2 }}
              >
                <Card className="group border-none shadow-none bg-white p-4 rounded-[2rem] hover:shadow-xl hover:shadow-blue-100/50 transition-all duration-500">
                  <CardContent className="p-8 space-y-6">
                    <div className="w-16 h-16 rounded-2xl bg-blue-50 flex items-center justify-center group-hover:scale-110 transition-transform duration-500">
                      {feature.icon}
                    </div>
                    <div>
                      <h3 className="text-2xl font-bold text-slate-900 mb-2">{feature.title}</h3>
                      <p className="text-slate-500 leading-relaxed font-medium">{feature.desc}</p>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export default Landing;